platform :ios, '14.0'

def capacitor_pods
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  use_frameworks!
  pod 'TensorFlowLiteSwift'
end

target 'PluginTests' do
  capacitor_pods
  use_frameworks!
  pod 'TensorFlowLiteSwift'
end
